version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::096281385844:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-c7qciJWJsNp3"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::096281385844:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-9sF0ud2vSoy8"
cloudformation_execution_role = "arn:aws:iam::096281385844:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-ChDNqvkFTMS9"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-xogqapqbxbqt"
image_repository = ""
region = "ap-southeast-2"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::096281385844:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-a4VAjRLMnRxx"
cloudformation_execution_role = "arn:aws:iam::096281385844:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-v0OAThREQ7mI"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-yuuhligecue4"
image_repository = ""
region = "ap-southeast-2"
